import { parseTokens } from "../domain/tokens";
import { handleHdfs } from "./handlers/hdfsCommands";
import { handleYarn } from "./handlers/yarnCommands";
import { handleHadoopJar } from "./handlers/hadoopJarCommands";

export function runMasterCommand(cmd, ctx) {
  const {
    out, cwd, services, hiveServices, localFS, permsMap, fsimageCounter,
    resolvePath, getLocalNode, ensureLocalDir, formatLs,
    setLocalFS, setCwd, setServices, setPermsMap, setSshNode, setSshCwd,
    setHiveServices, setBeelineMode, setBeelineConnected, resetAll, run,
  } = ctx;

  const trimmed = cmd.trim().replace(/\s*2>&1\s*$/, "");
  if (!trimmed) return [];

  const redir = trimmed.match(/^(.+?)\s*(>>|>)\s*(\S+)\s*$/);
  if (redir && !redir[3].startsWith("&")) {
    const leftCmd = redir[1].trim(); const isAppend = redir[2] === ">>"; const targetFile = redir[3];
    const lt = parseTokens(leftCmd); let outputText = "";
    if (lt[0] === "echo") { outputText = lt.slice(1).join(" ").replace(/['"]/g, ""); outputText = outputText.replace(/\$HADOOP_HOME/g, "/opt/hadoop").replace(/\$HOME/g, "/home/hadoop"); }
    else { const r = run(leftCmd); outputText = r.filter(x => x.type !== "clear").map(x => x.text).join("\n"); }
    const resolved = resolvePath(targetFile, cwd); const parent = resolved.substring(0, resolved.lastIndexOf("/")) || "/"; const name = resolved.substring(resolved.lastIndexOf("/") + 1);
    let nf = { ...localFS }; if (!nf[parent]) nf = ensureLocalDir(parent, nf); const existing = nf[parent]?.files?.[name] || "";
    nf[parent] = { ...nf[parent], files: { ...(nf[parent].files || {}), [name]: isAppend ? (existing ? existing + "\n" + outputText : outputText) : outputText }, children: [...new Set([...(nf[parent].children || []), name])] };
    setLocalFS(nf); return [];
  }
  const pipes = trimmed.split("|").map(s => s.trim()); const mainCmd = pipes[0]; const tokens = parseTokens(mainCmd); const base = tokens[0];

  if (base === "help") return [out("╔══════════════════════════════════════════════════════════════════╗\n║            SIMULADOR HADOOP — COMANDOS DISPONIBLES              ║\n╠══════════════════════════════════════════════════════════════════╣\n║ LINUX: ls [-l,-a,-r,-la,-lh], cd, pwd, mkdir [-p], touch,      ║\n║   cp [-r], mv, rm [-r,-f], cat, head, tail, grep, chmod [-R],  ║\n║   wc [-l,-w,-c], ps, top, hostname, uname, free, df, echo      ║\n║                                                                 ║\n║ SCRIPTS: echo 'cmd' >> script.sh · chmod u+x · ./script.sh     ║\n║ SSH: ssh nodo2 · ssh nodo3 (esclavos)                           ║\n║                                                                 ║\n║ SERVICIOS: ./start-dfs.sh  ./stop-dfs.sh                       ║\n║   ./start-yarn.sh  ./stop-yarn.sh  jps [-l]                    ║\n║                                                                 ║\n║ HDFS: hdfs dfs -ls/-mkdir/-put/-get/-cat/-rm/-chmod/-cp         ║\n║   hdfs dfs -createSnapshot/-deleteSnapshot                      ║\n║   hdfs dfsadmin -report/-safemode/-saveNamespace                ║\n║   hdfs fsck / [-files -blocks]                                  ║\n║                                                                 ║\n║ YARN: yarn node -list · yarn application -list/-status/-kill    ║\n║ MAPREDUCE: hadoop jar <jar> grep/wordcount/TestDFSIO            ║\n║                                                                 ║\n║ WEB UIs: Usa las pestañas HDFS(:9870) y YARN(:8088) arriba     ║\n║                                                                 ║\n║ HIVE: hiveserver2 (inicia servidor) · beeline (cliente)         ║\n║   !connect jdbc:hive2://hadoop-virtualbox:10000                 ║\n║   show databases; · create database <db>; · use <db>;           ║\n║   create table <t> (col tipo); · insert into <t> values (...);  ║\n║   select * from <t>; · describe <t>; · !tables · !exit          ║\n║                                                                 ║\n║ PERSISTENCIA: Progreso guardado · 'reset' para reiniciar       ║\n║ Tab: autocompleta · ↑↓: historial                              ║\n╚══════════════════════════════════════════════════════════════════╝", "help")];
  if (base === "clear") return [{ type: "clear" }];
  if (base === "pwd") return [out(cwd)]; if (base === "whoami") return [out("hadoop")]; if (base === "hostname") return [out("hadoop-VirtualBox")];
  if (base === "uname") return [out(tokens.includes("-a") ? "Linux hadoop-VirtualBox 5.15.0-91-generic #101-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux" : "Linux")];
  if (base === "lsb_release") return [out("Distributor ID: Ubuntu\nDescription:    Ubuntu 22.04.3 LTS\nRelease:        22.04\nCodename:       jammy")];
  if (base === "lscpu") return [out("Architecture:          x86_64\nCPU(s):                4\nModel name:            Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz")];
  if (base === "free") return [out("              total        used        free      shared  buff/cache   available\nMem:          8.0Gi       3.2Gi       2.1Gi       256Mi       2.7Gi       4.3Gi\nSwap:         2.0Gi          0B       2.0Gi")];
  if (base === "df") return [out("Filesystem      Size  Used Avail Use% Mounted on\n/dev/sda1        50G   18G   30G  38% /\n/dev/sda2       100G   25G   70G  27% /datos")];
  if (base === "ifconfig" || base === "ip") return [out("eth0: inet 192.168.56.10  netmask 255.255.255.0")];

  if (base === "reset") { resetAll(); return [out("✓ Estado reiniciado.", "success")]; }

  if (base === "echo") { const arg = tokens.slice(1).join(" ").replace(/['"]/g, ""); if (arg.includes("$(hadoop classpath)")) return [out("/opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*:/opt/hadoop/share/hadoop/mapreduce/*:/opt/hadoop/share/hadoop/yarn/*:/opt/hadoop/share/hadoop/yarn/lib/*")]; if (arg.includes("$HADOOP_HOME")) return [out("/opt/hadoop")]; if (arg.includes("$HOME")) return [out("/home/hadoop")]; if (arg.includes("$JAVA_HOME")) return [out("/usr/lib/jvm/java-11-openjdk-amd64")]; return [out(arg)]; }
  if (base === "wc") { const target = tokens.find((t, i) => i > 0 && !t.startsWith("-")); if (!target) return [out("wc: falta operando", "error")]; const nd = getLocalNode(resolvePath(target, cwd)); if (!nd || nd.type !== "file") return [out(`wc: ${target}: No existe`, "error")]; const c = nd.content || ""; const lc = c.split("\n").length; const wc = c.split(/\s+/).filter(Boolean).length; if (tokens.includes("-l")) return [out(`  ${lc} ${target}`)]; if (tokens.includes("-w")) return [out(`  ${wc} ${target}`)]; if (tokens.includes("-c")) return [out(`  ${c.length} ${target}`)]; return [out(`  ${lc}  ${wc} ${c.length} ${target}`)]; }
  if (base === "top") { const p = []; if (services.namenode) p.push("  1234 hadoop    20   0 1.2g 256m S  2.0  3.2 java (NameNode)"); if (services.datanode) p.push("  1235 hadoop    20   0 1.1g 200m S  1.5  2.5 java (DataNode)"); if (services.resourcemanager) p.push("  1236 hadoop    20   0 1.3g 300m S  3.0  3.7 java (ResourceManager)"); if (services.nodemanager) p.push("  1237 hadoop    20   0 1.0g 180m S  1.0  2.2 java (NodeManager)"); return [out(`top - 10:00:00 up 2 days, load average: 0.15, 0.10, 0.05\nTasks: ${120 + p.length} total\nMiB Mem: 8192.0 total, 2150.0 free, 3280.0 used\n\n  PID USER      PR  NI    VIRT    RES S  %CPU  %MEM COMMAND\n${p.join("\n")}`)]; }
  if (base === "ps") { let pl = "  PID TTY          TIME CMD\n 1000 pts/0    00:00:00 bash"; if (services.namenode) pl += "\n 1234 ?        00:00:45 java -Dproc_namenode"; if (services.datanode) pl += "\n 1235 ?        00:00:32 java -Dproc_datanode"; if (services.secondarynamenode) pl += "\n 1238 ?        00:00:12 java -Dproc_secondarynamenode"; if (services.resourcemanager) pl += "\n 1236 ?        00:00:58 java -Dproc_resourcemanager"; if (services.nodemanager) pl += "\n 1237 ?        00:00:22 java -Dproc_nodemanager"; if (services.historyserver) pl += "\n 1239 ?        00:00:08 java -Dproc_historyserver"; return [out(pl)]; }
  if (base === "jps") { const p = []; if (services.namenode) p.push("1234 NameNode"); if (services.datanode) p.push("1235 DataNode"); if (services.secondarynamenode) p.push("1238 SecondaryNameNode"); if (services.resourcemanager) p.push("1236 ResourceManager"); if (services.nodemanager) p.push("1237 NodeManager"); if (services.historyserver) p.push("1239 JobHistoryServer"); if (hiveServices.hiveserver2) p.push("1250 HiveServer2"); p.push(`${1240 + p.length} Jps`); if (tokens.includes("-l")) { const fqn = { NameNode: "org.apache.hadoop.hdfs.server.namenode.NameNode", DataNode: "org.apache.hadoop.hdfs.server.datanode.DataNode", SecondaryNameNode: "org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode", ResourceManager: "org.apache.hadoop.yarn.server.resourcemanager.ResourceManager", NodeManager: "org.apache.hadoop.yarn.server.nodemanager.NodeManager", JobHistoryServer: "org.apache.hadoop.mapreduce.v2.hs.JobHistoryServer", HiveServer2: "org.apache.hive.service.server.HiveServer2", Jps: "sun.tools.jps.Jps" }; return [out(p.map(x => { const [pid, nm] = x.split(" "); return `${pid} ${fqn[nm] || nm}`; }).join("\n"))]; } return [out(p.join("\n"))]; }
  if (base === "cd") { const t = tokens[1] || "~"; const r = resolvePath(t, cwd); const nd = getLocalNode(r); if (!nd && !localFS[r]) return [out(`bash: cd: ${t}: No existe`, "error")]; if (nd?.type === "file") return [out(`bash: cd: ${t}: No es un directorio`, "error")]; setCwd(r); return []; }

  if (base === "ls") { const af = tokens.filter((t, i) => i > 0 && t.startsWith("-")).map(f => f.replace(/^-+/, "")).join(""); const targets = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (targets.length === 0) { const r = formatLs(cwd, af); return r ? [out(r)] : []; } if (targets.length === 1) { const r = resolvePath(targets[0], cwd); const nd = getLocalNode(r); if (!nd && !localFS[r]) return [out(`ls: '${targets[0]}': No existe`, "error")]; if (nd?.type === "file") { if (af.includes("l")) return [out(`-rw-r--r-- 1 hadoop hadoop ${(nd.content || "").length} Feb 28 10:00 ${targets[0]}`)]; return [out(targets[0])]; } const res = formatLs(r, af); return res ? [out(res)] : []; } const results = []; for (let ti = 0; ti < targets.length; ti++) { const r = resolvePath(targets[ti], cwd); const nd = getLocalNode(r); if (!nd && !localFS[r]) { results.push(out(`ls: '${targets[ti]}': No existe`, "error")); continue; } if (nd?.type === "file") { results.push(out(targets[ti])); continue; } const body = formatLs(r, af) || ""; results.push(out((ti > 0 ? "\n" : "") + `${targets[ti]}:\n${body}`)); } return results; }
  if (base === "mkdir") { const dirs = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (dirs.length === 0) return [out("mkdir: falta operando", "error")]; let nf = { ...localFS }; for (const d of dirs) { const r = resolvePath(d, cwd); if (!nf[r]) nf = ensureLocalDir(r, nf); } setLocalFS(nf); return []; }
  if (base === "touch") { const files = tokens.slice(1).filter(t => !t.startsWith("-")); let nf = { ...localFS }; for (const f of files) { const r = resolvePath(f, cwd); const par = r.substring(0, r.lastIndexOf("/")) || "/"; const nm = r.substring(r.lastIndexOf("/") + 1); if (!nf[par]) nf = ensureLocalDir(par, nf); if (nf[par]) nf[par] = { ...nf[par], files: { ...(nf[par].files || {}), [nm]: "" }, children: [...new Set([...(nf[par].children || []), nm])] }; } setLocalFS(nf); return []; }
  if (base === "cat") { const targets = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (targets.length === 0) return [out("cat: falta operando", "error")]; let c = ""; for (let fi = 0; fi < targets.length; fi++) { const nd = getLocalNode(resolvePath(targets[fi], cwd)); if (!nd) return [out(`cat: ${targets[fi]}: No existe`, "error")]; if (nd.type === "dir") return [out(`cat: ${targets[fi]}: Es un directorio`, "error")]; if (fi > 0) c += "\n"; c += nd.content || ""; } for (let pi = 1; pi < pipes.length; pi++) { const pt = pipes[pi].trim(); if (pt.startsWith("head")) { const n = parseInt(pt.match(/-n?\s*(\d+)/)?.[1] || pt.match(/-(\d+)/)?.[1]) || 10; c = c.split("\n").slice(0, n).join("\n"); } else if (pt.startsWith("tail")) { const n = parseInt(pt.match(/-n?\s*(\d+)/)?.[1] || pt.match(/-(\d+)/)?.[1]) || 10; c = c.split("\n").slice(-n).join("\n"); } else if (pt.startsWith("wc")) { const ls = c.split("\n").length; const ws = c.split(/\s+/).filter(Boolean).length; c = pt.includes("-l") ? `  ${ls}` : pt.includes("-w") ? `  ${ws}` : `  ${ls}  ${ws} ${c.length}`; } else if (pt.startsWith("grep")) { const gt = parseTokens(pt); const gf = gt.filter(t => t.startsWith("-")).map(t => t.replace(/^-+/, "")).join(""); const pat = gt.find((t, i) => i > 0 && !t.startsWith("-")) || ""; try { const re = new RegExp(pat, gf.includes("i") ? "gi" : "g"); let matched = c.split("\n").filter(l => re.test(l)); if (gf.includes("v")) matched = c.split("\n").filter(l => !new RegExp(pat, gf.includes("i") ? "gi" : "g").test(l)); if (gf.includes("c")) c = String(matched.length); else c = matched.join("\n"); } catch { c = `grep: regex inválida`; } } else if (pt.startsWith("sort")) { const lines = c.split("\n"); lines.sort(); if (pt.includes("-r")) lines.reverse(); c = lines.join("\n"); } else if (pt.startsWith("uniq")) { c = c.split("\n").filter((l, i, a) => i === 0 || l !== a[i - 1]).join("\n"); } } return [out(c)]; }
  if (base === "head") { const target = tokens.find((t, i) => i > 0 && !t.startsWith("-")); if (!target) return [out("head: falta operando", "error")]; let n = 10; const nf2 = tokens.find(t => /^-\d+$/.test(t)); const dn = tokens.indexOf("-n"); if (nf2) n = parseInt(nf2.slice(1)); else if (dn >= 0 && tokens[dn + 1]) n = parseInt(tokens[dn + 1]); const nd = getLocalNode(resolvePath(target, cwd)); if (!nd || nd.type !== "file") return [out(`head: ${target}: No existe`, "error")]; return [out((nd.content || "").split("\n").slice(0, n).join("\n"))]; }
  if (base === "tail") { const target = tokens.find((t, i) => i > 0 && !t.startsWith("-")); if (!target) return [out("tail: falta operando", "error")]; let n = 10; const nf2 = tokens.find(t => /^-\d+$/.test(t)); const dn = tokens.indexOf("-n"); if (nf2) n = parseInt(nf2.slice(1)); else if (dn >= 0 && tokens[dn + 1]) n = parseInt(tokens[dn + 1]); const nd = getLocalNode(resolvePath(target, cwd)); if (!nd || nd.type !== "file") return [out(`tail: ${target}: No existe`, "error")]; return [out((nd.content || "").split("\n").slice(-n).join("\n"))]; }
  if (base === "grep") { const gf = tokens.filter(t => t.startsWith("-")).map(t => t.replace(/^-+/, "")).join(""); const pos = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); const pattern = pos[0]; const gT = pos.slice(1); if (!pattern || gT.length === 0) return [out("Usage: grep PATTERN FILE", "error")]; const results = []; for (const t of gT) { const nd = getLocalNode(resolvePath(t, cwd)); if (!nd || nd.type !== "file") { results.push(out(`grep: ${t}: No existe`, "error")); continue; } try { const re = new RegExp(pattern, gf.includes("i") ? "gi" : "g"); let m = (nd.content || "").split("\n").filter(l => re.test(l)); if (gf.includes("v")) m = (nd.content || "").split("\n").filter(l => !new RegExp(pattern, gf.includes("i") ? "gi" : "g").test(l)); if (gf.includes("c")) { results.push(out(`${gT.length > 1 ? t + ":" : ""}${m.length}`)); continue; } const pf = gT.length > 1 ? t + ":" : ""; results.push(out(m.length > 0 ? m.slice(0, 50).map(l => pf + l).join("\n") : `(sin coincidencias)`)); } catch { results.push(out(`grep: regex inválida`, "error")); } } return results; }
  if (base === "cp") { const cf = tokens.filter(t => t.startsWith("-")).map(t => t.replace(/^-+/, "")).join(""); const pos = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (pos.length < 2) return [out("cp: faltan operandos", "error")]; const dst = pos[pos.length - 1]; const srcs = pos.slice(0, -1); let nf = { ...localFS }; const dstR = resolvePath(dst, cwd); const dstIsDir = !!nf[dstR]; for (const src of srcs) { const srcR = resolvePath(src, cwd); const srcN = getLocalNode(srcR); if (!srcN) return [out(`cp: '${src}': No existe`, "error")]; const srcName = srcR.substring(srcR.lastIndexOf("/") + 1); if (srcN.type === "file") { const tp = dstIsDir ? dstR : (dstR.substring(0, dstR.lastIndexOf("/")) || "/"); const tn = dstIsDir ? srcName : dstR.substring(dstR.lastIndexOf("/") + 1); if (!nf[tp]) nf = ensureLocalDir(tp, nf); nf[tp] = { ...nf[tp], files: { ...(nf[tp].files || {}), [tn]: srcN.content }, children: [...new Set([...(nf[tp].children || []), tn])] }; } else if (localFS[srcR]) { if (!cf.includes("r")) return [out(`cp: se omite directorio '${src}' (usa -r)`, "error")]; const tb = dstIsDir ? `${dstR}/${srcName}` : dstR; nf = ensureLocalDir(tb, nf); nf[tb] = { ...nf[tb], children: [...(localFS[srcR].children || [])], files: { ...(localFS[srcR].files || {}) } }; } } setLocalFS(nf); return []; }
  if (base === "mv") { const pos = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (pos.length < 2) return [out("mv: faltan operandos", "error")]; const dst = pos[pos.length - 1]; const srcs = pos.slice(0, -1); let nf = { ...localFS }; const dstR = resolvePath(dst, cwd); const dstIsDir = !!nf[dstR]; for (const src of srcs) { const srcR = resolvePath(src, cwd); const srcPar = srcR.substring(0, srcR.lastIndexOf("/")) || "/"; const srcName = srcR.substring(srcR.lastIndexOf("/") + 1); const srcN = getLocalNode(srcR); if (!srcN) return [out(`mv: '${src}': No existe`, "error")]; const tp = dstIsDir ? dstR : (dstR.substring(0, dstR.lastIndexOf("/")) || "/"); const tn = dstIsDir ? srcName : dstR.substring(dstR.lastIndexOf("/") + 1); if (!nf[tp]) nf = ensureLocalDir(tp, nf); if (srcN.type === "file") { nf[tp] = { ...nf[tp], files: { ...(nf[tp].files || {}), [tn]: srcN.content }, children: [...new Set([...(nf[tp].children || []), tn])] }; if (nf[srcPar]?.files) { const { [srcName]: _, ...rest } = nf[srcPar].files; nf[srcPar] = { ...nf[srcPar], files: rest, children: (nf[srcPar].children || []).filter(c => c !== srcName) }; } } else if (localFS[srcR]) { const np = dstIsDir ? `${dstR}/${srcName}` : dstR; nf[np] = { ...nf[srcR] }; delete nf[srcR]; Object.keys(nf).forEach(k => { if (k.startsWith(srcR + "/")) { nf[np + k.substring(srcR.length)] = nf[k]; delete nf[k]; } }); if (nf[srcPar]) nf[srcPar] = { ...nf[srcPar], children: (nf[srcPar].children || []).filter(c => c !== srcName) }; } } setLocalFS(nf); return []; }
  if (base === "rm") { const rf = tokens.filter(t => t.startsWith("-")).map(t => t.replace(/^-+/, "")).join(""); const targets = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (targets.length === 0) return [out("rm: falta operando", "error")]; let nf = { ...localFS }; for (const t of targets) { const r = resolvePath(t, cwd); const par = r.substring(0, r.lastIndexOf("/")) || "/"; const nm = r.substring(r.lastIndexOf("/") + 1); if (nf[r]?.type === "dir") { if (!rf.includes("r")) return [out(`rm: '${t}': Es un directorio (usa -r)`, "error")]; Object.keys(nf).forEach(k => { if (k === r || k.startsWith(r + "/")) delete nf[k]; }); if (nf[par]) nf[par] = { ...nf[par], children: (nf[par].children || []).filter(c => c !== nm) }; } else if (nf[par]?.files?.[nm] !== undefined) { const { [nm]: _, ...rest } = nf[par].files; nf[par] = { ...nf[par], files: rest, children: (nf[par].children || []).filter(c => c !== nm) }; } else if (!rf.includes("f")) return [out(`rm: '${t}': No existe`, "error")]; } setLocalFS(nf); return []; }
  if (base === "chmod") { const chF = tokens.filter(t => t.startsWith("-")).map(t => t.replace(/^-+/, "")).join(""); const pos = tokens.filter((t, i) => i > 0 && !t.startsWith("-")); if (pos.length < 2) return [out("chmod: falta operando", "error")]; const mode = pos[0]; const targets = pos.slice(1); const np = { ...permsMap }; const numToRwx = (n) => { const d = String(n).padStart(3, "0"); const m = { "0": "---", "1": "--x", "2": "-w-", "3": "-wx", "4": "r--", "5": "r-x", "6": "rw-", "7": "rwx" }; return (m[d[0]] || "---") + (m[d[1]] || "---") + (m[d[2]] || "---"); }; for (const t of targets) { const r = resolvePath(t, cwd); const paths = [r]; if (chF.includes("R") && localFS[r]) { Object.keys(localFS).forEach(k => { if (k.startsWith(r + "/")) paths.push(k); }); } for (const p of paths) { if (/^\d{3,4}$/.test(mode)) { np[p] = numToRwx(mode.length === 4 ? mode.slice(1) : mode); } else if (mode.includes("+x")) { const cur = np[p] || "rw-r--r--"; np[p] = cur.substring(0, 2) + "x" + cur.substring(3); } else if (mode.includes("-x")) { const cur = np[p] || "rwxr-xr-x"; np[p] = cur.replace(/x/g, "-"); } else np[p] = mode; } } setPermsMap(np); return []; }

  if (base === "ssh") { const target = (tokens[1] || "").replace("hadoop@", ""); if (target === "nodo2" || target === "nodo3") { if (!services.namenode) return [out(`ssh: connect to host ${target}: Connection refused`, "error")]; setSshNode(target); setSshCwd("/home/hadoop"); return [out(`Warning: Permanently added '${target}' (ECDSA) to known hosts.\nWelcome to Ubuntu 22.04.3 LTS (${target})\n`, "success")]; } if (target === "hadoop-VirtualBox" || target === "localhost") return [out("(Ya estás en hadoop-VirtualBox)", "warn")]; return [out(`ssh: Could not resolve hostname ${target}`, "error")]; }
  if (base === "scp") return [out("scp: archivo copiado al nodo remoto (simulado).", "success")];
  if (base === "md5sum") { const target = tokens.slice(1).join(" "); if (!target) return []; const mkH = () => Array.from({ length: 32 }, () => "0123456789abcdef"[Math.floor(Math.random() * 16)]).join(""); if (target.includes("fsimage")) { const r = []; for (let i = 42; i <= fsimageCounter; i++) r.push(`${mkH()}  /datos/namenode/current/fsimage_${String(i).padStart(19, "0")}`); return [out(r.slice(-4).join("\n"))]; } return [out(`${mkH()}  ${target}`)]; }

  if (trimmed === "./start-dfs.sh" || trimmed === "start-dfs.sh" || trimmed.endsWith("/start-dfs.sh")) { setServices(s => ({ ...s, namenode: true, datanode: true, secondarynamenode: true })); return [out("Starting namenodes on [hadoop-VirtualBox]\nnodo2: starting datanode\nnodo3: starting datanode\nStarting secondary namenodes [hadoop-VirtualBox]\n\n✓ HDFS iniciado. Web UI → pestaña HDFS(:9870)", "success")]; }
  if (trimmed === "./stop-dfs.sh" || trimmed === "stop-dfs.sh" || trimmed.endsWith("/stop-dfs.sh")) { setServices(s => ({ ...s, namenode: false, datanode: false, secondarynamenode: false })); return [out("Stopping namenodes\nStopping datanodes\n\n✓ HDFS detenido.", "warn")]; }
  if (trimmed === "./start-yarn.sh" || trimmed === "start-yarn.sh" || trimmed.endsWith("/start-yarn.sh")) { if (!services.namenode) return [out("WARN: HDFS no está activo.", "error")]; setServices(s => ({ ...s, resourcemanager: true, nodemanager: true })); return [out("Starting resourcemanager\nnodo2: starting nodemanager\nnodo3: starting nodemanager\n\n✓ YARN iniciado. Web UI → pestaña YARN(:8088)", "success")]; }
  if (trimmed === "./stop-yarn.sh" || trimmed === "stop-yarn.sh" || trimmed.endsWith("/stop-yarn.sh")) { setServices(s => ({ ...s, resourcemanager: false, nodemanager: false })); return [out("Stopping resourcemanager\nStopping nodemanagers\n\n✓ YARN detenido.", "warn")]; }
  if (base === "mapred" && tokens[1] === "historyserver") { if (!services.resourcemanager) return [out("Error: YARN no está activo.", "error")]; setServices(s => ({ ...s, historyserver: true })); return [out("✓ JobHistoryServer en http://hadoop-VirtualBox:19888", "success")]; }

  if (base === "hdfs") return handleHdfs(tokens, pipes, ctx);
  if (base === "yarn") return handleYarn(tokens, pipes, ctx);
  if (base === "hadoop" && (tokens[1] === "fs" || tokens[1] === "dfs")) return run("hdfs dfs " + tokens.slice(2).join(" "));
  if (base === "hadoop" && tokens[1] === "jar") return handleHadoopJar(tokens, pipes, ctx);

  if (base === "javac") { const f = tokens.find(t => t.endsWith(".java")); if (!f) return [out("javac: no source files", "error")]; const nm = f.replace(".java", ""); let nf = { ...localFS }; if (nf[cwd]) { const cls = [`${nm}.class`, `${nm}$TokenizerMapper.class`, `${nm}$IntSumReducer.class`]; nf[cwd] = { ...nf[cwd], children: [...new Set([...(nf[cwd].children || []), ...cls])], files: { ...(nf[cwd].files || {}), ...Object.fromEntries(cls.map(c => [c, `[bytecode: ${c}]`])) } }; } setLocalFS(nf); return [out(`✓ Compilación exitosa`, "success")]; }
  if (base === "jar" && tokens[1] === "cf") { const jn = tokens[2]; if (!jn) return [out("jar: faltan argumentos", "error")]; let nf = { ...localFS }; if (nf[cwd]) nf[cwd] = { ...nf[cwd], children: [...new Set([...(nf[cwd].children || []), jn])], files: { ...(nf[cwd].files || {}), [jn]: `[JAR: ${jn}]` } }; setLocalFS(nf); return [out(`✓ ${jn} creado`, "success")]; }
  if (base === "gzip") {
    const keep = tokens.includes("-k"); const decomp = tokens.includes("-d");
    const target = tokens.find((t, i) => i > 0 && !t.startsWith("-"));
    if (!target) return [out("gzip: falta operando", "error")];
    const r = resolvePath(target, cwd); const nd = getLocalNode(r);
    if (!nd || nd.type !== "file") return [out(`gzip: ${target}: No existe`, "error")];
    if (decomp || target.endsWith(".gz")) return run(`gunzip ${target}`);
    const gzName = target.endsWith(".gz") ? target : target + ".gz";
    const par = r.substring(0, r.lastIndexOf("/")) || "/"; const nm = r.substring(r.lastIndexOf("/") + 1);
    let nf = { ...localFS };
    nf[par] = { ...nf[par], children: [...new Set([...(nf[par].children || []).filter(c => keep || c !== nm), gzName])], files: { ...(nf[par].files || {}), [gzName]: `[gzip compressed: ${nm}]\n${nd.content || ""}` } };
    if (!keep) { const { [nm]: _, ...rest } = nf[par].files || {}; nf[par] = { ...nf[par], files: rest }; }
    setLocalFS(nf); return [out(`gzip: ${target} → ${gzName}`, "success")];
  }
  if (base === "gunzip") {
    const keep = tokens.includes("-k");
    const target = tokens.find((t, i) => i > 0 && !t.startsWith("-"));
    if (!target) return [out("gunzip: falta operando", "error")];
    if (!target.endsWith(".gz")) return [out(`gunzip: ${target}: unknown suffix -- ignored`, "error")];
    const r = resolvePath(target, cwd); const nd = getLocalNode(r);
    if (!nd || nd.type !== "file") return [out(`gunzip: ${target}: No existe`, "error")];
    const outName = target.slice(0, -3);
    const par = r.substring(0, r.lastIndexOf("/")) || "/"; const nm = r.substring(r.lastIndexOf("/") + 1);
    const rawContent = (nd.content || "").replace(/^\[gzip compressed: [^\]]+\]\n/, "");
    let nf = { ...localFS };
    const newChildren = [...new Set([...(nf[par].children || []).filter(c => keep || c !== nm), outName])];
    nf[par] = { ...nf[par], children: newChildren, files: { ...(nf[par].files || {}), [outName]: rawContent } };
    if (!keep) { const { [nm]: _, ...rest } = nf[par].files; nf[par] = { ...nf[par], files: rest }; }
    setLocalFS(nf); return [out(`gunzip: ${target} → ${outName}`, "success")];
  }
  if (base === "exit") return [out("(Nodo maestro. Usa 'reset' para reiniciar.)", "warn")];
  if (base === "hiveserver2") {
    if (!services.namenode) return [out("Error: HDFS no está activo.", "error")];
    if (!services.resourcemanager) return [out("Error: YARN no está activo.", "error")];
    setHiveServices(s => ({ ...s, hiveserver2: true }));
    return [out("2026-03-03 10:00:00 INFO  hive.metastore: Starting Hive Metastore Server\n2026-03-03 10:00:01 INFO  service.CompositeService: Starting HiveServer2\n2026-03-03 10:00:02 INFO  thrift.ThriftCLIService: Starting ThriftBinaryCLIService on port 10000\n2026-03-03 10:00:03 INFO  http.HttpServer: Started HiveServer2 Web UI on port 10002\n\n✓ HiveServer2 activo en puerto 10000\n  Web UI → pestaña Hive(:10002)", "success")];
  }
  if (base === "beeline") {
    if (!hiveServices.hiveserver2) return [out("Error: HiveServer2 no está activo.\nInicia primero:\n  cd /opt/hadoop/hive/bbdd\n  hiveserver2", "error")];
    setBeelineMode(true);
    setBeelineConnected(false);
    return [out("Beeline version 4.0.0 by Apache Hive\nbeeline>", "system")];
  }
  if (["nano", "vim", "vi", "gedit"].includes(base)) return [out(`(${base} no disponible. Usa echo >> archivo y cat.)`, "warn")];
  if (base === "bash" || base === "sh") { const sp = tokens[1]; if (!sp) return [out(`${base}: falta archivo`, "error")]; const nd = getLocalNode(resolvePath(sp, cwd)); if (!nd || nd.type !== "file") return [out(`${base}: ${sp}: No existe`, "error")]; const sLines = (nd.content || "").split("\n").filter(l => l.trim() && !l.trim().startsWith("#")); const results = []; for (const line of sLines) results.push(...run(line.trim())); return results; }
  if (base.startsWith("./")) { const sn = base.substring(2); const r = resolvePath(sn, cwd); const nd = getLocalNode(r); if (!nd || nd.type !== "file") return [out(`bash: ${base}: No existe`, "error")]; const pm = permsMap[r] || "rw-r--r--"; if (!pm.includes("x")) return [out(`bash: ${base}: Permiso denegado\nTip: chmod u+x ${sn}`, "error")]; const sLines = (nd.content || "").split("\n").filter(l => l.trim() && !l.trim().startsWith("#")); const results = []; for (const line of sLines) results.push(...run(line.trim())); return results.length === 0 ? [out(`(script ${sn} ejecutado)`, "success")] : results; }
  return [out(`bash: ${base}: comando no encontrado`, "error")];
}
