import { genBenchmark } from "../../domain/logGenerators";

export function handleHadoopJar(tokens, pipes, ctx) {
  const { out, services, hdfsFS, appCounter, ensureHdfsDir, setHdfsFS, setAppCounter, setYarnApps } = ctx;
  if (!services.resourcemanager) return [out("Error: YARN no está activo.", "error")];
  const jar = tokens[2] || ""; const jt = tokens[3] || "";
  if (jar.includes("tests.jar") || jt === "TestDFSIO") { const mode = tokens.includes("-write") ? "write" : "read"; const nrF = parseInt(tokens.find((t, i) => tokens[i - 1] === "-nrFiles") || "10"); const fS = parseInt(tokens.find((t, i) => tokens[i - 1] === "-fileSize") || "100"); const aid = appCounter; setAppCounter(c => c + 1); setYarnApps(prev => [...prev, { id: aid, name: `TestDFSIO-${mode}`, state: "FINISHED" }]); let nf = ensureHdfsDir("/benchmarks/TestDFSIO", { ...hdfsFS }); nf[`/benchmarks/TestDFSIO/io_${mode}`] = { type: "file", content: genBenchmark(mode, nrF, fS), size: 512, owner: "hadoop", group: "supergroup" }; if (!nf["/benchmarks"].children.includes("TestDFSIO")) nf["/benchmarks"] = { ...nf["/benchmarks"], children: [...nf["/benchmarks"].children, "TestDFSIO"] }; setHdfsFS(nf); return [out(`Job completed successfully.\n\n${genBenchmark(mode, nrF, fS)}`, "success")]; }
  if (jt === "grep") { const inp = tokens[4]; const outp = tokens[5]; const regex = tokens.slice(6).join(" ").replace(/^['"]|['"]$/g, ""); if (!inp || !outp) return [out("Usage: hadoop jar <jar> grep <in> <out> '<regex>'", "error")]; if (hdfsFS[outp]) return [out(`Output ${outp} already exists. Bórralo: hdfs dfs -rm -r ${outp}`, "error")]; const inode = hdfsFS[inp]; if (!inode) return [out(`Input path not found: ${inp}`, "error")]; let all = ""; if (inode.type === "dir") { for (const ch of (inode.children || [])) { const cp = `${inp}/${ch}`; if (hdfsFS[cp]?.content) all += hdfsFS[cp].content + "\n"; } } else all = inode.content || ""; let matches = {}; try { const re = new RegExp(regex, "gi"); for (const line of all.split("\n")) { const m = line.match(re); if (m) for (const x of m) matches[x.toLowerCase()] = (matches[x.toLowerCase()] || 0) + 1; } } catch {} const sorted = Object.entries(matches).sort((a, b) => b[1] - a[1]); const rc = sorted.length > 0 ? sorted.map(([k, v]) => `${v}\t${k}`).join("\n") : "(sin coincidencias)"; let nf = ensureHdfsDir(outp, { ...hdfsFS }); nf[`${outp}/part-r-00000`] = { type: "file", content: rc, size: rc.length, owner: "hadoop", group: "supergroup" }; nf[`${outp}/_SUCCESS`] = { type: "file", content: "", size: 0, owner: "hadoop", group: "supergroup" }; nf[outp] = { ...nf[outp], children: [...new Set([...(nf[outp].children || []), "part-r-00000", "_SUCCESS"])] }; setHdfsFS(nf); const aid = appCounter; setAppCounter(c => c + 1); setYarnApps(prev => [...prev, { id: aid, name: "grep-search", state: "FINISHED" }]); return [out(`Job completed successfully.\n\n✓ Verifica: hdfs dfs -cat ${outp}/part-r-00000 | head`, "success")]; }
  if (tokens.length >= 5) { const inp = tokens[tokens.length - 2]; const outp = tokens[tokens.length - 1]; if (hdfsFS[outp]) return [out(`Output ${outp} already exists.`, "error")]; const inode = hdfsFS[inp]; if (!inode) return [out(`Input not found: ${inp}`, "error")]; let all = ""; if (inode.type === "dir") { for (const ch of (inode.children || [])) { const p = `${inp}/${ch}`; if (hdfsFS[p]?.content) all += hdfsFS[p].content + "\n"; } } else all = inode.content || ""; const words = {}; all.split(/\s+/).filter(Boolean).forEach(w => { const k = w.replace(/[^a-zA-Z0-9_.-]/g, ""); if (k) words[k] = (words[k] || 0) + 1; }); const rc = Object.entries(words).sort((a, b) => a[0].localeCompare(b[0])).map(([k, v]) => `${k}\t${v}`).join("\n"); let nf = ensureHdfsDir(outp, { ...hdfsFS }); nf[`${outp}/part-r-00000`] = { type: "file", content: rc, size: rc.length, owner: "hadoop", group: "supergroup" }; nf[`${outp}/_SUCCESS`] = { type: "file", content: "", size: 0, owner: "hadoop", group: "supergroup" }; nf[outp] = { ...nf[outp], children: ["part-r-00000", "_SUCCESS"] }; setHdfsFS(nf); const aid = appCounter; setAppCounter(c => c + 1); setYarnApps(prev => [...prev, { id: aid, name: jt || "wordcount", state: "FINISHED" }]); return [out(`Job completed successfully.\n\n✓ Verifica: hdfs dfs -cat ${outp}/part-r-00000 | head`, "success")]; }
  if (jar.includes("examples") && !jt) return [out(`An example program must be given as the first argument.\nValid program names are:\n  aggregatewordcount: An Aggregate based map/reduce program that counts the words in the input files.\n  aggregatewordhist: An Aggregate based map/reduce program that computes the histogram of the words in the input files.\n  bbp: A map/reduce program that uses Bailey-Borwein-Plouffe to compute exact digits of Pi.\n  dbcount: An example job that count the pageview counts from a database.\n  distbbp: A map/reduce program that uses Bailey-Borwein-Plouffe to compute exact digits of Pi.\n  grep: A map/reduce program that counts the matches of a regex in the input.\n  join: A job that effects a join over sorted, equally partitioned datasets\n  multifilewc: A job that counts words from several files.\n  pentomino: A map/reduce tile laying program to find solutions to pentomino problems.\n  pi: A map/reduce program that estimates Pi using a quasi-Monte Carlo method.\n  randomtextwriter: A map/reduce program that writes 10GB of random textual data per node.\n  randomwriter: A map/reduce program that writes 10GB of random data per node.\n  secondarysort: An example defining a secondary sort to the reduce.\n  sort: A map/reduce program that sorts the data written by the random writer.\n  sudoku: A sudoku solver.\n  teragen: Generate data for the terasort\n  terasort: Run the terasort\n  teravalidate: Checking results of terasort\n  wordcount: A map/reduce program that counts the words in the input files.\n  wordmean: A map/reduce program that counts the average length of the words in the input files.\n  wordmedian: A map/reduce program that counts the median length of the words in the input files.\n  wordstandarddeviation: A map/reduce program that counts the standard deviation of the length of the words in the input files.`, "output")];
  return [out(`Usage: hadoop jar <jar> [mainClass] args...`, "error")];
}
