export function handleHdfs(tokens, pipes, ctx) {
  const { out, services, hdfsFS, localFS, cwd, safeMode, fsimageCounter, hdfsSnapEnabled } = ctx;
  const { resolvePath, getLocalNode, ensureHdfsDir, setHdfsFS, setLocalFS, setSafeMode, setFsimageCounter, setHdfsSnapEnabled, setHdfsSnapshots } = ctx;

  if (!services.namenode) return [out("✗ HDFS no iniciado. Ejecuta: ./start-dfs.sh", "error")];
  const sub = tokens[1];
  if (sub === "dfs") {
    const flag = tokens[2];
    if (flag === "-ls") { const t = tokens[3] || "/"; const n = hdfsFS[t]; if (!n) return [out(`ls: '${t}': No such file or directory`, "error")]; if (n.type === "dir") { const items = n.children || []; if (items.length === 0) return [out("Found 0 items")]; return [out(`Found ${items.length} items\n${items.map(i => { const cp = t === "/" ? `/${i}` : `${t}/${i}`; const cn = hdfsFS[cp]; if (cn?.type === "dir") return `drwxr-xr-x   - hadoop supergroup          0 2026-02-28 10:00 ${cp}`; return `-rw-r--r--   2 hadoop supergroup     ${String(cn?.size || 1024).padStart(8)} 2026-02-28 10:00 ${cp}`; }).join("\n")}`)]; } return [out(`-rw-r--r--   2 hadoop supergroup     ${n.size || 0} 2026-02-28 10:00 ${t}`)]; }
    if (flag === "-mkdir") { let nf = { ...hdfsFS }; for (const p of tokens.slice(3).filter(t => !t.startsWith("-"))) nf = ensureHdfsDir(p, nf); setHdfsFS(nf); return []; }
    if (flag === "-put") { const lp = tokens[3]; const hp = tokens[4]; if (!lp || !hp) return [out("Usage: hdfs dfs -put <localsrc> <dst>", "error")]; const rl = resolvePath(lp, cwd); const ln = getLocalNode(rl); if (!ln) return [out(`put: '${lp}': No such file or directory\n  (ruta resuelta: ${rl})`, "error")]; let nf = { ...hdfsFS }; const hpp = hp.replace(/\/$/, ""); if (!nf[hpp]) nf = ensureHdfsDir(hpp, nf); if (ln.type === "file") { const fn = rl.substring(rl.lastIndexOf("/") + 1); const fp = `${hpp}/${fn}`; nf[fp] = { type: "file", content: ln.content, size: (ln.content || "").length, owner: "hadoop", group: "supergroup" }; if (nf[hpp]) nf[hpp] = { ...nf[hpp], children: [...new Set([...(nf[hpp].children || []), fn])] }; } setHdfsFS(nf);
      const sd0 = "/datos/datanode/current/BP-1234567890-127.0.0.1-1700000000000/current/finalized/subdir0/subdir0";
      const blkId = Date.now();
      const blkName = `blk_${blkId}`; const metaName = `blk_${blkId}_1001.meta`;
      setLocalFS(prev => { const nlfs = { ...prev }; const dir = nlfs[sd0] || { type: "dir", children: [], files: {} }; nlfs[sd0] = { ...dir, children: [...new Set([...(dir.children || []), blkName, metaName])], files: { ...(dir.files || {}), [blkName]: ln.content || "", [metaName]: `\x00\x01\x02\x00\x00${blkId}` } }; return nlfs; });
      return []; }
    if (flag === "-get") { const hs = tokens[3]; const ld = tokens[4] || "."; const hn = hdfsFS[hs]; if (!hn) return [out(`get: '${hs}': No such file`, "error")]; const rd = resolvePath(ld, cwd); const fn = hs.substring(hs.lastIndexOf("/") + 1); let nf = { ...localFS }; const tp = nf[rd] ? rd : (rd.substring(0, rd.lastIndexOf("/")) || "/"); const tn = nf[rd] ? fn : rd.substring(rd.lastIndexOf("/") + 1); if (!nf[tp]) nf = ctx.ensureLocalDir(tp, nf); nf[tp] = { ...nf[tp], files: { ...(nf[tp].files || {}), [tn]: hn.content || "" }, children: [...new Set([...(nf[tp].children || []), tn])] }; setLocalFS(nf); return []; }
    if (flag === "-cat") { const t = tokens[3]; if (!t) return [out("cat: falta ruta", "error")]; const n = hdfsFS[t]; if (!n) return [out(`cat: '${t}': No such file`, "error")]; let c = n.content || ""; for (let pi = 1; pi < pipes.length; pi++) { const pt = pipes[pi].trim(); if (pt.startsWith("head")) { const num = parseInt(pt.match(/-n?\s*(\d+)/)?.[1] || pt.match(/-(\d+)/)?.[1]) || 10; c = c.split("\n").slice(0, num).join("\n"); } else if (pt.startsWith("tail")) { const num = parseInt(pt.match(/-n?\s*(\d+)/)?.[1] || pt.match(/-(\d+)/)?.[1]) || 10; c = c.split("\n").slice(-num).join("\n"); } } return [out(c)]; }
    if (flag === "-rm") { const rec = tokens.includes("-r"); const t = tokens.find((x, i) => i > 2 && !x.startsWith("-")); if (!t) return [out("rm: falta ruta", "error")]; let nf = { ...hdfsFS }; const par = t.substring(0, t.lastIndexOf("/")) || "/"; const nm = t.substring(t.lastIndexOf("/") + 1); if (rec) Object.keys(nf).forEach(k => { if (k === t || k.startsWith(t + "/")) delete nf[k]; }); else delete nf[t]; if (nf[par]) nf[par] = { ...nf[par], children: (nf[par].children || []).filter(c => c !== nm) }; setHdfsFS(nf); return [out(`Deleted ${t}`)]; }
    if (flag === "-chmod") return [];
    if (flag === "-cp") { const aa = tokens.slice(3).filter(t => !t.startsWith("-")); if (aa.length < 2) return [out("cp: faltan operandos", "error")]; const d = aa[aa.length - 1]; const ss = aa.slice(0, -1); let nf = { ...hdfsFS }; for (const s of ss) { if (s.includes("*")) { const dir = s.substring(0, s.lastIndexOf("/")); const dn2 = nf[dir]; if (dn2) for (const ch of (dn2.children || [])) { const sp = `${dir}/${ch}`; if (nf[sp]) { if (!nf[d]) nf = ensureHdfsDir(d, nf); nf[`${d}/${ch}`] = { ...nf[sp] }; nf[d] = { ...nf[d], children: [...new Set([...(nf[d].children || []), ch])] }; } } } else { const sn2 = nf[s]; if (sn2) { const nm = s.substring(s.lastIndexOf("/") + 1); if (!nf[d]) nf = ensureHdfsDir(d, nf); nf[`${d}/${nm}`] = { ...sn2 }; nf[d] = { ...nf[d], children: [...new Set([...(nf[d].children || []), nm])] }; } } } setHdfsFS(nf); return []; }
    if (flag === "-createSnapshot") { const dir = tokens[3]; const sn = tokens[4]; if (!dir || !sn) return [out("Usage: hdfs dfs -createSnapshot <dir> <name>", "error")]; if (!hdfsSnapEnabled.has(dir)) return [out(`${dir}: Not snapshottable. Use hdfs dfsadmin -allowSnapshot ${dir}`, "error")]; if (!hdfsFS[dir]) return [out(`createSnapshot: '${dir}': No such file`, "error")]; const ss = {}; Object.keys(hdfsFS).forEach(k => { if (k === dir || k.startsWith(dir + "/")) ss[k] = { ...hdfsFS[k] }; }); setHdfsSnapshots(prev => ({ ...prev, [`${dir}/${sn}`]: ss })); let nf = { ...hdfsFS }; const sd = `${dir}/.snapshot`; if (!nf[sd]) nf[sd] = { type: "dir", children: [sn], owner: "hadoop", group: "supergroup" }; else nf[sd] = { ...nf[sd], children: [...new Set([...(nf[sd].children || []), sn])] }; const sp = `${sd}/${sn}`; const on = nf[dir]; nf[sp] = { type: "dir", children: [...(on.children || [])], owner: "hadoop", group: "supergroup" }; for (const ch of (on.children || [])) { const src = `${dir}/${ch}`; if (nf[src]) nf[`${sp}/${ch}`] = { ...nf[src] }; } setHdfsFS(nf); return [out(`Created snapshot ${sd}/${sn}`, "success")]; }
    if (flag === "-deleteSnapshot") { const dir = tokens[3]; const sn = tokens[4]; setHdfsSnapshots(prev => { const n = { ...prev }; delete n[`${dir}/${sn}`]; return n; }); let nf = { ...hdfsFS }; const sd = `${dir}/.snapshot`; if (nf[sd]) nf[sd] = { ...nf[sd], children: (nf[sd].children || []).filter(c => c !== sn) }; delete nf[`${sd}/${sn}`]; setHdfsFS(nf); return [out(`Deleted snapshot ${sn}`, "success")]; }
    return [out(`hdfs dfs: Unknown command: ${flag}`, "error")];
  }
  if (sub === "dfsadmin") {
    const flag = tokens[2];
    if (flag === "-report") { const u = Object.keys(hdfsFS).filter(k => hdfsFS[k].type === "file").length; return [out(`Configured Capacity: 107374182400 (100.00 GB)\nDFS Used: ${(u * 1024).toLocaleString()}\nLive datanodes (3):\n\nName: 192.168.56.10:9866 (hadoop-VirtualBox)\nName: 192.168.56.11:9866 (nodo2)\nName: 192.168.56.12:9866 (nodo3)`)]; }
    if (flag === "-safemode") { const a = tokens[3]; if (a === "enter") { setSafeMode(true); return [out("Safe mode is ON", "warn")]; } if (a === "leave") { setSafeMode(false); return [out("Safe mode is OFF", "success")]; } if (a === "get") return [out(`Safe mode is ${safeMode ? "ON" : "OFF"}`)]; return [out("Usage: -safemode enter|leave|get", "error")]; }
    if (flag === "-saveNamespace") { if (!safeMode) return [out("saveNamespace: Safe mode should be ON", "error")]; const nc = fsimageCounter + 1; setFsimageCounter(nc); let nf = { ...localFS }; const fi = `fsimage_${String(nc).padStart(19, "0")}`; const md = fi + ".md5"; const ed = `edits_inprogress_${String(nc + 1).padStart(19, "0")}`; const mkH = () => Array.from({ length: 32 }, () => "0123456789abcdef"[Math.floor(Math.random() * 16)]).join(""); nf["/datos/namenode/current"] = { ...nf["/datos/namenode/current"], children: [...(nf["/datos/namenode/current"]?.children || []), fi, md, ed], files: { ...(nf["/datos/namenode/current"]?.files || {}), [fi]: "[binary fsimage]", [md]: mkH(), [ed]: "[binary edits]" } }; setLocalFS(nf); return [out(`Save namespace successful. New fsimage: ${fi}`, "success")]; }
    if (flag === "-allowSnapshot") { const d = tokens[3]; if (!hdfsFS[d]) return [out(`'${d}': No such file`, "error")]; setHdfsSnapEnabled(prev => new Set([...prev, d])); return [out(`Allowing snapshot on ${d} succeeded`, "success")]; }
    if (flag === "-disallowSnapshot") { const d = tokens[3]; setHdfsSnapEnabled(prev => { const n = new Set(prev); n.delete(d); return n; }); return [out(`Disallowing snapshot on ${d}`, "success")]; }
    return [out(`hdfs dfsadmin: Unknown: ${flag}`, "error")];
  }
  if (sub === "fsck") { const t = tokens[2] || "/"; const det = tokens.includes("-files"); const fc = Object.keys(hdfsFS).filter(k => hdfsFS[k].type === "file").length; const dc = Object.keys(hdfsFS).filter(k => hdfsFS[k].type === "dir").length; let r = `FSCK started by hadoop for path ${t}`; if (det) Object.keys(hdfsFS).filter(k => hdfsFS[k].type === "file").forEach(k => { r += `\n${k} ${hdfsFS[k].size || 1024} bytes, replication=2, 1 block(s): OK`; }); r += `\n\nStatus: HEALTHY\n Total size: ${fc * 1024} B\n Total dirs: ${dc}\n Total files: ${fc}\n\nThe filesystem under path '${t}' is HEALTHY`; return [out(r)]; }
  return [out(`hdfs: Unknown command: ${sub}`, "error")];
}
