export function handleYarn(tokens, pipes, ctx) {
  const { out, services, yarnApps, setYarnApps } = ctx;
  if (!services.resourcemanager) return [out("✗ YARN no iniciado. Ejecuta: ./start-yarn.sh", "error")];
  const sub = tokens[1];
  if (sub === "node") { let o = "Total Nodes:3\n  Node-Id\tNode-State\tNode-Http-Address\nhadoop-VirtualBox:45454\tRUNNING\thadoop-VirtualBox:8042\nnodo2:45454\t\tRUNNING\tnodo2:8042\nnodo3:45454\t\tRUNNING\tnodo3:8042"; if (tokens.includes("-showDetails") || tokens.includes("--showDetails")) o += "\n\n  hadoop-VirtualBox — Memory: 3200/4096 MB, VCores: 1/4\n  nodo2 — Memory: 1500/4096 MB, VCores: 0/2\n  nodo3 — Memory: 1500/4096 MB, VCores: 0/2"; return [out(o)]; }
  if (sub === "application") { const f = tokens[2]; if (f === "-list") { const active = yarnApps.filter(a => !["KILLED"].includes(a.state)); if (active.length === 0) return [out("Total number of applications: 0")]; return [out(`Total number of applications: ${active.length}\n${active.map(a => `application_1700000000000_${String(a.id).padStart(4, "0")}\t${a.name}\tMAPREDUCE\t${a.state}`).join("\n")}`)]; } if (f === "-status") { const aid = tokens[3]; const idn = parseInt(aid?.split("_").pop()); const app = yarnApps.find(a => a.id === idn); if (!app) return [out(`Application '${aid}' doesn't exist.`, "error")]; return [out(`Application-Id : ${aid}\nApplication-Name : ${app.name}\nState : ${app.state}\nFinal-State : ${app.state === "FINISHED" ? "SUCCEEDED" : "UNDEFINED"}\nProgress : ${app.state === "FINISHED" ? "100" : "0"}%`)]; } if (f === "-kill") { const aid = tokens[3]; const idn = parseInt(aid?.split("_").pop()); setYarnApps(prev => prev.map(a => a.id === idn ? { ...a, state: "KILLED" } : a)); return [out(`✓ Application ${aid} killed.`, "success")]; } return [out(`yarn application: Unknown: ${f}`, "error")]; }
  if (sub === "applicationattempt") { const aid = tokens[3]; if (!aid) return [out("Usage: yarn applicationattempt -list <App ID>", "error")]; return [out(`Total attempts: 1\nappattempt_${aid.replace("application_", "")}_000001\tRUNNING`)]; }
  if (sub === "container") { const atid = tokens[3]; if (!atid) return [out("Usage: yarn container -list <Attempt Id>", "error")]; const cid = atid.replace("appattempt_", ""); return [out(`Total containers: 2\ncontainer_${cid}_000001\tRUNNING\thadoop-VirtualBox:45454\ncontainer_${cid}_000002\tRUNNING\tnodo2:45454`)]; }
  return [out(`yarn: Unknown: ${sub}`, "error")];
}
